/**
 * Schema 3: DI su RAG ir įrankiais – mazgų paaiškinimai.
 * Sluoksniai: Pagrindinis srautas (įvestis–DI–išvestis), Įrankiai, Duomenys.
 * Paprasta kalba – žr. PAPRASTOS_KALBOS_GAIRES.
 */

export type Schema3StepExplanation = { title: string; body: string };

export const SCHEMA3_STEP_EXPLANATIONS: Schema3StepExplanation[] = [
  {
    title: 'Įvestis',
    body: '**Pagrindinis srautas.** Klausimas arba užduotis, kurią vartotojas pateikia DI. Pvz. „Kokios buvo Lietuvos eksporto tendencijos 2024 m.?“ – tai įvestis, kuri nukreipia visą sistemą.',
  },
  {
    title: 'DI',
    body: '**Pagrindinis srautas.** Didelis kalbos modelis (DI) – centrinis valdymo taškas. Apdoroja įvestį, nusprendžia, ar reikia įrankio (informacijos gavimas), ar atsakyti tiesiai iš savo žinių.',
  },
  {
    title: 'Išvestis',
    body: '**Pagrindinis srautas.** DI sugeneruotas atsakymas – tekstas, vaizdas ar kita informacija. Priklauso nuo to, ar DI naudojo įrankius, ar tik savo žinias.',
  },
  {
    title: 'Įrankių naudojimas',
    body: '**Įrankiai.** DI kviečia išorinius įrankius – paiešką (gauti duomenis iš šaltinių). Valdymas eina iš DI, vykdymas – čia. Sąveika dvipusė.',
  },
  {
    title: 'Informacijos gavimas',
    body: '**Įrankiai.** Paima duomenis iš išorinio šaltinio (duomenų bazės, dokumentų). Tai RAG pagrindas – paėmimas iš saugyklos prieš atsakymą. Kontekstas tiekiamas į modelį.',
  },
  {
    title: 'Duomenų bazė / saugykla',
    body: '**Duomenys (atminties sluoksnis).** Išorinis šaltinis – dokumentai, duomenys, žinių bazė. Informacijos gavimas čia skaito ir tiekia kontekstą. Pasirinktinai DI gali įrašyti informaciją į saugyklą (punktyrinė rodyklė). Be šios grandies DI remiasi tik savo mokymosi duomenimis.',
  },
];

export const SCHEMA3_STEP_EXPLANATIONS_EN: Schema3StepExplanation[] = [
  {
    title: 'Input',
    body: '**Main flow.** The question or task the user gives to the LLM. E.g. “What were Lithuania’s export trends in 2024?” is the input that drives the whole system.',
  },
  {
    title: 'LLM',
    body: '**Main flow.** The large language model (LLM) is the central control point. It processes the input and decides whether to use a tool (e.g. retrieval) or answer directly from its knowledge.',
  },
  {
    title: 'Output',
    body: '**Main flow.** The response generated by the LLM – text, image or other information. Depends on whether the LLM used tools or only its own knowledge.',
  },
  {
    title: 'Tool use',
    body: '**Tools.** The LLM calls external tools – e.g. search (to get data from sources). Control comes from the LLM; execution happens here. The interaction is two-way.',
  },
  {
    title: 'Information retrieval',
    body: '**Tools.** Fetches data from an external source (database, documents). This is the basis of RAG – fetching from storage before answering. Context is supplied to the model.',
  },
  {
    title: 'Database / storage',
    body: '**Data (memory layer).** External source – documents, data, knowledge base. Retrieval reads from here and supplies context. Optionally the LLM can write information to storage (dashed arrow). Without this link the LLM relies only on its training data.',
  },
];

export type Schema3Locale = 'lt' | 'en';

export function getSchema3StepExplanations(locale: Schema3Locale): Schema3StepExplanation[] {
  return locale === 'en' ? SCHEMA3_STEP_EXPLANATIONS_EN : SCHEMA3_STEP_EXPLANATIONS;
}
